import type { SVGProps } from 'react'
// Tech framework and service icons from react-icons
import {
  SiNextdotjs,
  SiVercel,
  SiReact,
  SiTypescript,
  SiTailwindcss,
  SiNodedotjs,
  SiPrisma,
  SiSupabase,
  SiAmazon,
  SiGooglecloud,
  SiDocker,
  SiKubernetes,
  SiGithub,
  SiGitlab,
  SiFigma,
  SiStripe,
  SiDrizzle,
  SiFirebase,
  SiPlanetscale,
  SiCloudflare,
  SiNetlify,
  SiRailway,
  SiVuedotjs,
  SiNuxtdotjs,
  SiGo,
  SiPayloadcms,
  SiLinux,
  SiMacos,
  SiRust,
  SiZig,
  SiCplusplus,
  SiSvelte,
  SiElixir,
  SiPostgresql,
  SiTauri,
  SiDotnet,
  SiRaspberrypi,
  SiRedis,
} from 'react-icons/si'

function NeonIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 64 64" fill="currentColor" {...props}>
      <path d="M63 0.018V63.553L38.418 42.25V63.553H0V0L63 0.018ZM7.723 55.839H30.695V25.324L55.278 47.048V7.729L7.723 7.716V55.839Z" />
    </svg>
  )
}

// Export all tech icons with consistent naming
export const TechIcons = {
  NextJS: SiNextdotjs,
  Vercel: SiVercel,
  React: SiReact,
  TypeScript: SiTypescript,
  TailwindCSS: SiTailwindcss,
  NodeJS: SiNodedotjs,
  Prisma: SiPrisma,
  Supabase: SiSupabase,
  AWS: SiAmazon,
  GoogleCloud: SiGooglecloud,
  Docker: SiDocker,
  Kubernetes: SiKubernetes,
  GitHub: SiGithub,
  GitLab: SiGitlab,
  Figma: SiFigma,
  Stripe: SiStripe,
  Drizzle: SiDrizzle,
  Firebase: SiFirebase,
  PlanetScale: SiPlanetscale,
  Cloudflare: SiCloudflare,
  Netlify: SiNetlify,
  Railway: SiRailway,
  Vue: SiVuedotjs,
  Nuxt: SiNuxtdotjs,
  Go: SiGo,
  PayloadCMS: SiPayloadcms,
  Linux: SiLinux,
  macOS: SiMacos,
  Rust: SiRust,
  Zig: SiZig,
  CPlusPlus: SiCplusplus,
  Svelte: SiSvelte,
  Elixir: SiElixir,
  PostgreSQL: SiPostgresql,
  Tauri: SiTauri,
  DotNet: SiDotnet,
  Neon: NeonIcon,
  RaspberryPi: SiRaspberrypi,
  Redis: SiRedis,
} as const
